apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.APP_NAME }}-network-policy
  namespace: {{ .Values.NAMESPACE }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.APP_NAME }}
  policyTypes: ["Ingress", "Egress"]
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 8080
      protocol: TCP
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Values.APP_NAME }}-db
    ports:
    - port: 5432
      protocol: TCP