apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.APP_NAME }}-pdb
  namespace: {{ .Values.NAMESPACE }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Values.APP_NAME }}